# Generated by Django 4.1.2 on 2022-10-11 19:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('name', models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Years', 'Years')], default='Day', max_length=255)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('payload', models.TextField(max_length=500)),
                ('SSL', models.CharField(default='none', max_length=255)),
                ('proxyIP', models.CharField(max_length=255)),
                ('proxyport', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Payload',
                'verbose_name_plural': 'Payload',
                'db_table': 'Payload',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Flag', models.ImageField(upload_to='flag/')),
                ('Server_Host', models.CharField(max_length=255)),
                ('Server_Port', models.CharField(max_length=255)),
                ('SSL_Port', models.CharField(max_length=255)),
                ('UDP_port', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'db_table': 'Server',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.PositiveIntegerField()),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transaction',
                'db_table': 'Transaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServerJson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.ManyToManyField(to='Dashboard.payload')),
                ('server', models.ManyToManyField(to='Dashboard.server')),
            ],
            options={
                'verbose_name': 'ServerJson',
                'verbose_name_plural': 'ServerJsons',
                'db_table': 'ServerJson',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(default=datetime.datetime.now)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.membership')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customer',
                'managed': True,
            },
        ),
    ]
