# Generated by Django 4.1.1 on 2022-09-26 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('name', models.CharField(choices=[('Trial', 'Trial'), ('Day', 'Day'), ('Month', 'Month'), ('Years', 'Years')], default='Trial', max_length=255)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('jsondata', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'update',
                'verbose_name_plural': 'updates',
                'db_table': 'update',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(default=datetime.datetime.now)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.membership')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'Customer',
                'managed': True,
            },
        ),
    ]
