# Generated by Django 4.1.1 on 2022-09-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='ststua',
            new_name='status',
        ),
    ]
