# Generated by Django 4.1.1 on 2022-09-20 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_rename_ststua_update_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True),
        ),
    ]
