# Generated by Django 4.1.1 on 2022-09-20 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_update_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
