# Generated by Django 4.1.1 on 2022-09-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_membership_name_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='dredit',
            new_name='balance',
        ),
    ]
