# Generated by Django 4.1.1 on 2022-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_alter_update_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='passcode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
