# Generated by Django 4.1.1 on 2022-09-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_update_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='passcode',
        ),
    ]
