# Generated by Django 4.1.1 on 2022-09-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_remove_update_passcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('name', models.CharField(choices=[('Trial', 'Trial'), ('Day', 'Day'), ('Month', 'Month'), ('Years', 'Years')], default='Trial', max_length=255)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
    ]
