# Generated by Django 4.1.1 on 2022-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
