# Generated by Django 4.1.1 on 2022-09-24 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
