# Generated by Django 4.1.1 on 2022-09-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_alter_customer_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.membership'),
            preserve_default=False,
        ),
    ]
