# Generated by Django 4.1.1 on 2022-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginapp', '0002_user_createby_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
