# Generated by Django 4.1.1 on 2022-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginapp', '0004_alter_user_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
